# basic
backend_dir: backend
script_dir: script

# about file
file_save_dir: upload
upload_dna_save_dir: upload_dna

file_type:
 - picture
 - music
 - txt
 - pdf
 - video

# about run
encode_dir: encode

# min free energy
min_free_energy: /usr/local/bin/RNAfold

# about simulation
simulation_dir: simulation

# decode
starcode_local: /data2/dna/Software/starcode/starcode
starcode_remote: /Users/jianglikun/VScode/DNAStorage
cdhit: /home/dna/Software/cdhit-4.8.1/cd-hit
decode_dir: decode

# threads
threads: 30