# basic
backend_dir: backend
script_dir: script

# about file
file_save_dir: upload
upload_dna_save_dir: upload_dna

# demo file
demo_dir: demo

# about run
encode_dir: encode

# min free energy
min_free_energy: /usr/local/bin/RNAfold

# about simulation
simulation_dir: simulation

# decode
starcode: /data2/dna/Software/starcode/starcode
cdhit: /home/dna/Software/cdhit-4.8.1/cd-hit
decode_dir: decode

# threads
threads: 20