# basic
backend_dir: backend
script_dir: script

# about file
file_save_dir: upload
upload_dna_save_dir: upload

file_type:
 - picture
 - music
 - txt
 - pdf
 - video

# about run
encode_dir: encode

# about simulation
simulation_dir: simulation

# decode
decode_dir: decode