# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /opt/recipe, last modified Sat Oct 26 11:48:15 2019
# ------------------------------------------------

package:
    name: cd-hit
    version: 4.8.1
source:
    sha256: f8bc3cdd7aebb432fcd35eed0093e7a6413f1e36bbd2a837ebc06e57cdb20b70
    url: https://github.com/weizhongli/cdhit/archive/V4.8.1.tar.gz
build:
    number: '3'
    string: h8b12597_3
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h7fc9f1b_2
        - binutils_linux-64 2.31.1 h6176602_12
        - gcc_impl_linux-64 7.3.0 habb00fd_2
        - gcc_linux-64 7.3.0 h553295d_12
        - gxx_impl_linux-64 7.3.0 hdf63c60_2
        - gxx_linux-64 7.3.0 h553295d_12
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - llvm-openmp 8.0.1 hc9558a2_0
        - openmp 8.0.1 0
        - zlib 1.2.11 h516909a_1006
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - openmp
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - cd-hit --help | grep 'Usage' > /dev/null
about:
    home: https://github.com/weizhongli/cdhit
    license: GPLv2
    summary: Clusters and compares protein or nucleotide sequences
extra:
    copy_test_source_files: true
    final: true
